force-app/main/default/objects/Issue__c/Issue__c.object-meta.xml
<CustomObject>
    <label>Issue</label>
    <nameField>
        <displayFormat>ISS-{YYYY}{MM}-{0000}</displayFormat>
        <label>IssueNumber</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Issues</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Issue__c/fields/ClosedDate__c.field-meta.xml
<CustomField>
    <fullName>ClosedDate__c</fullName>
    <label>ClosedDate</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Issue__c/fields/WasClosed__c.field-meta.xml
<CustomField>
    <fullName>WasClosed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>WasClosed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/tool_IssueTriggerHandlerTest.cls
@IsTest
public with sharing class tool_IssueTriggerHandlerTest {
  private static Issue__c createIssue() {
    Issue__c issue = new Issue__c(
      Subject__c = 'Test',
      Description__c = 'This is a test.'
    );

    insert issue;

    return issue;
  }

  @testSetup
  static void setup() {
    createIssue();
  }

  static testMethod void constructor_ShouldBeFalseOnCreation() {
    Issue__c actual = null;

    Test.startTest();
    actual = createIssue();
    Test.stopTest();

    System.assertEquals(false, actual.WasClosed__c);
  }

  static testMethod void constructor_ShouldFail() {
    Issue__c issue = [Select Id, ClosedDate__c From Issue__c Limit 1];

    Test.startTest();
    issue.ClosedDate__c = Date.today();
    Test.stopTest();

    System.assertEquals(true, issue.WasClosed__c);
  }
}